import { SensorEvent, DecisionResult, DecisionAction } from "../../types/intelligence";
import { TriggerSource, IncidentSeverity } from "../../types/packet";
import { SensorFusion } from "./SensorFusion";
import { EmergencyConfidenceCalculator } from "./EmergencyConfidenceCalculator";
import { EmergencyTimeline } from "./EmergencyTimeline";
import { PacketBuilder, PacketQueue } from "../packet";

export const DecisionEngine = {
  /**
   * Master Pipeline Evaluator
   * Ingests physical sensor events, runs fusion arithmetic, computes ECS, records timeline ledger,
   * and dispatches appropriate actions to the Packet Engine or UI warning systems.
   */
  evaluateSensorEvent: async (event: SensorEvent): Promise<DecisionResult> => {
    // 1. Ingest event into multi-sensor fusion correlation window
    SensorFusion.pushEvent(event);
    await EmergencyTimeline.logEvent(
      "SENSOR_DETECTED",
      `Ingested ${event.type} from ${event.sourceProvider}`,
      { magnitude: event.magnitude, confidence: event.confidence }
    );

    // 2. Evaluate compound accident pattern across sliding window
    const pattern = SensorFusion.evaluatePattern();
    await EmergencyTimeline.logEvent(
      "CONTEXT_EVALUATED",
      pattern.patternDescription,
      { eventsInWindow: pattern.compoundEvents.length, maxMagnitude: pattern.maxMagnitude }
    );

    // 3. Calculate standardized Emergency Confidence Score (ECS)
    const scoreRes = EmergencyConfidenceCalculator.computeScore(pattern);
    const ecs = scoreRes.score;

    await EmergencyTimeline.logEvent(
      "SCORE_CALCULATED",
      `Computed ECS of ${ecs}/100 based on sensor fusion and context weights.`,
      scoreRes.breakdown,
      ecs
    );

    // 4. Determine authoritative Decision Action based on ECS rules
    let action: DecisionAction = "IGNORE";
    let computedSeverity: IncidentSeverity = "INFO";
    let recommendationText = "Transient event; below triage threshold. No action required.";
    let triggerSource: TriggerSource = "MULTI_SENSOR_FALL";

    if (event.type === "IMPACT_DETECTED" && event.magnitude > 15) {
      triggerSource = "VEHICLE_CRASH";
    }

    if (ecs >= 85) {
      action = "GENERATE_SOS_PACKET";
      computedSeverity = "CRITICAL";
      recommendationText = "CRITICAL EMERGENCY CONFIRMED: Bypassing manual check-in to instantly generate and queue immutable SOS distress packet for wireless mesh relay.";
      
      // Immediately construct and queue the emergency broadcast via Phase 1.5 Packet Engine!
      const emergencyPacket = await PacketBuilder.buildEmergencyPacket({
        emergencyType: pattern.hasFreeFall ? "Compound Fall & Immobility" : "High-G Vehicular Impact / Collision",
        severity: computedSeverity,
        ecs: ecs,
        isAutomatic: true,
        triggerSource,
        additionalDescription: `Auto-generated by Phase 2A Intelligence Engine. ${pattern.patternDescription}`,
      });

      await PacketQueue.enqueue(emergencyPacket);
      await EmergencyTimeline.logEvent(
        "PACKET_GENERATED",
        `Generated emergency packet ${emergencyPacket.header.packetId} and placed into priority mesh outbox queue!`,
        { packetId: emergencyPacket.header.packetId, ecs },
        ecs
      );

      // Reset buffer so we don't duplicate packets in the same immediate window
      SensorFusion.clearBuffer();

    } else if (ecs >= 65) {
      action = "START_COUNTDOWN";
      computedSeverity = "HIGH";
      recommendationText = "HIGH LIKELIHOOD ACCIDENT: Initiating interactive 30-second acoustic alarm countdown before emergency packet transmission.";
      
      await EmergencyTimeline.logEvent(
        "COUNTDOWN_STARTED",
        "Started 30-second pre-broadcast alarm countdown.",
        { triggerSource, ecs },
        ecs
      );

    } else if (ecs >= 35) {
      action = "WARN_USER";
      computedSeverity = "MODERATE";
      recommendationText = "MODERATE ANOMALY: Displaying polite status check-in dialog to verify responder safety.";
      
      await EmergencyTimeline.logEvent(
        "USER_WARNED",
        "Displayed status check-in warning prompt to user.",
        { triggerSource, ecs },
        ecs
      );
    }

    const result: DecisionResult = {
      action,
      emergencyConfidenceScore: ecs,
      computedSeverity,
      primaryTrigger: triggerSource,
      recommendationText,
      timestamp: new Date().toISOString(),
      eventId: event.id,
    };

    return result;
  },

  /**
   * Manual override allowing simulated tests or UI buttons to reset active decision logic
   */
  resetEngine: (): void => {
    SensorFusion.clearBuffer();
  }
};
